version: '3'

services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
    networks:
      - default

  php:
    build:
      context: ./bin/php
      args:
        PHP_VERSION: ${PHP_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        MORE_EXTENSION_INSTALLER: php.sh
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_LOG_DIR}:/var/log/php
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - default

  mongo:
    image: mongo:${MONGO_VERSION}
    ports:
      - "${MONGO_HOST_PORT}:27017"
    volumes:
      - ${MONGO_DATA_DB_DIR}:/data/db:rw
    restart: always
    networks:
      - default

  ### 以下是可选项

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "${PHPMYADMIN_HOST_PORT}:80"
    networks:
      - default
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    ports:
      - "${REDISMYADMIN_HOST_PORT}:80"
    networks:
      - default
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_HOST_PORT}:8081"

  ## mongo rs
  mongo-rs-1:
    image: mongo:${MONGO_RS_VERSION}
    ports:
      - "${MONGO_RS_1_HOST_PORT}:27017"
    volumes:
      - ${MONGO_RS_1_DATA_DB_DIR}:/data/db:rw
    restart: always
    networks:
      - default
    command: "mongod --dbpath /data/db --replSet ${MONGO_RS_NAME} --oplogSize 1 --bind_ip_all"

  mongo-rs-2:
    image: mongo:${MONGO_RS_VERSION}
    ports:
      - "${MONGO_RS_2_HOST_PORT}:27017"
    volumes:
      - ${MONGO_RS_2_DATA_DB_DIR}:/data/db:rw
    networks:
      - default
    command: "mongod --dbpath /data/db --replSet ${MONGO_RS_NAME} --oplogSize 1 --bind_ip_all"

  mongo-rs-3:
    image: mongo:${MONGO_RS_VERSION}
    ports:
      - "${MONGO_RS_3_HOST_PORT}:27017"
    volumes:
      - ${MONGO_RS_3_DATA_DB_DIR}:/data/db:rw
    restart: always
    networks:
      - default
    command: "mongod --dbpath /data/db --replSet ${MONGO_RS_NAME} --oplogSize 1 --bind_ip_all"

  mongo-rs-setup:
    image: mongo:${MONGO_RS_VERSION}
    depends_on:
      - "mongo-rs-1"
      - "mongo-rs-2"
      - "mongo-rs-3"
    links:
      - mongo-rs-1:mongo-rs-1
      - mongo-rs-2:mongo-rs-2
      - mongo-rs-3:mongo-rs-3
    volumes:
      - ${MONGO_RS_SCRIPTS_DIR}:/scripts
    restart: always
    networks:
      - default
    environment:
      - RS=${MONGO_RS_NAME}
    entrypoint: "/scripts/setup.sh"

networks:
  default:
